### ISSUE TITLE
Unable to Install Modules from Repositories in version 0.16.0

### ISSUE THREAD

**Issue by hashaway** [ezra-bible-app/ezra-bible-app#155] opened 2020-12-22 14:31 UTC
**I am able** to update the repository data, but I am **not able** to install modules from the repositories. It gives me the following message on every attempt to install either a Bible Translation or a Dictionary:

> "...failed. Are you connected to the Internet?"

I installed the application today for the first time, and I do have the x86 version of "Microsoft Visual C++ 2015 Redistributable" installed. 

Can you please test this on your side and advise me accordingly?

Thank you for making this application available and for the work that you are doing. I am looking forward to using this software :o)

**Comment by tobias-klein** [comment] 2020-12-22 17:01
Thanks for raising this!
Which Windows version are you using?
Which repository and module were you facing this issue with?
I've been mostly testing on Windows 10 and there I could not reproduce your issue just now.

**Comment by tobias-klein** [comment] 2020-12-22 17:34
I just did a short test on Windows 7 Enterprise Service Pack 1 (32 Bit) and there I could not reproduce this issue. I could successfully install a module from the eBible repository.

**Comment by hashaway** [comment] 2020-12-23 10:09
> Thanks for raising this!
> Which Windows version are you using?
> Which repository and module were you facing this issue with?
> I've been mostly testing on Windows 10 and there I could not reproduce your issue just now.

Thank you for testing and responding.

I am using Windows 7 Home Premium SP1
CrossWire: American King James Version; American Standard Version (1901) - (I have tried most of the repositories and various translation modules and dictionary modules).

**Comment by tobias-klein** [comment] 2020-12-23 10:36
Thanks. Do you get *some* progress (via progress bar indicator) when attempting to install a module or does it give you the error message immediately?
It could technically be a network issue based on a timeout. Likely the root cause is in the SWORD library, but to be sure I need some more information.
Did you try other SWORD frontends and does it work there? (Like BibleTime or Xiphos)

**Comment by hashaway** [comment] 2020-12-23 10:37
> I just did a short test on Windows 7 Enterprise Service Pack 1 (32 Bit) and there I could not reproduce this issue. I could successfully install a module from the eBible repository.

I am using the **64bit** Windows 7 Home Premium SP1.
I installed the vc_redist.x86.exe version of the "Microsoft Visual C++ 2015 Redistributable" (as per the instruction provided within the Ezra Project "prompt/dialog window" during installation of the "Ezra Project Application"). Ordinarily I would have wanted to install tvc_redist.x64.exe instead of vc_redist.x86.exe because I am using a 64bit computer.

Here are Five Screenshots:

Screenshot 1:
![Screenshot 1](https://user-images.githubusercontent.com/34164202/102986071-dcbf7a80-4518-11eb-8838-787e8acd6529.png)

Screenshot 2:
![Screenshot 2](https://user-images.githubusercontent.com/34164202/102986117-f8c31c00-4518-11eb-9c6b-8ef2c9d0c2d5.png)

Screenshot 3:
![Screenshot 3](https://user-images.githubusercontent.com/34164202/102986153-08dafb80-4519-11eb-9a9f-acfa56102930.png)

Screenshot 4:
![Screenshot 4](https://user-images.githubusercontent.com/34164202/102986588-c36afe00-4519-11eb-8f6c-f6240bbc01c9.png)

Screenshot 5: (The screen changes to blank after a few seconds when the software processes the instructions to attempt to download the second module).
![Screenshot 5](https://user-images.githubusercontent.com/34164202/102986637-d1208380-4519-11eb-87b7-f19391ccaa23.png)

Screenshot 6: (This is what my internet activity looks like after making three attempts to go through the aforementioned steps seen in the previous screenshots). (There is only minor packet "upload" communication, but no download packet transfer taking place).
![Screenshot 6](https://user-images.githubusercontent.com/34164202/102986841-1f358700-451a-11eb-85d3-58aa56e885bb.png)

Screenshot 7: (This is my attempt to download ONLY one module. As you can see, there is NO blank screen, and I am able to click on the Finish button).
![Screenshot 7](https://user-images.githubusercontent.com/34164202/102987222-b26ebc80-451a-11eb-8093-36ef048c9be0.png)

Screenshot 8: (This is the resultant screen, when I click on the Finish Button displayed in "Screenshot 7"):
![Screenshot 8](https://user-images.githubusercontent.com/34164202/102987430-f235a400-451a-11eb-8f95-a080bb8ca8ca.png)

Please Note: That I have 8GB RAM, plenty hard drive space and a very stable computer that gives me NO problems. I do not ordinarily experience problems with installing and running software on my system. It is a very reliable computer. I also disabled security software.

Any advice that you may have, will be appreciated. Thank you for your assistance so far.

**Comment by hashaway** [comment] 2020-12-23 10:42
> Thanks. Do you get _some_ progress (via progress bar indicator) when attempting to install a module or does it give you the error message immediately?
> It could technically be a network issue based on a timeout. Likely the root cause is in the SWORD library, but to be sure I need some more information.
> Did you try other SWORD frontends and does it work there? (Like BibleTime or Xiphos)

There is no indication of progress via the progress bar indicator, but it does take a little while before it gives the error message. (Never immediately).
I have not tried other SWORD frontends, but I will do so within the next 24 hours and report back to you. I am going to log off now, and will get back to you as soon as possible.

**Comment by tobias-klein** [comment] 2020-12-23 10:49
Thanks for the additional feedback and all the screenshots! This is very helpful!
The other frontends should technically run into the same issue if the root cause is in the SWORD library. One other thing that could be checked is the network performance of a manual download of the respective modules from the given repos. I'm going to check whether I can post the URLs here, so that you can check.
If it ends up being a timeout issue I can possibly adjust a parameter for controlling the timeout and fix it that way.

**Comment by tobias-klein** [comment] 2020-12-23 12:41
I could actually just reproduce the behavior by imposing enforced packet delays on the network adapter of my test machine. The crash only happens on Windows, but it's good that I could reproduce it.

**Comment by reyespinosa1996** [comment] 2020-12-23 12:50
I've being following the discussion and since the beginning it looks like a timeout issue for a lag of response due to ISP issues or delay response on the server hand. I think a client side time out parameter longer than a few seconds  should allow low speed connection to succeed.

**Comment by tobias-klein** [comment] 2020-12-23 13:33
@hashaway
I think there is a workaround that you could apply to avoid this issue. Do the following:

1) Open the file `C:\Users\<your-user-name>\AppData\Roaming\sword\installMgr\InstallMgr.conf` in a text editor that can handle unix line breaks (like Notepad++).
2) Under `[General]` there should already be an entry `TimeoutMillis=`. Set this to a value greater than 10000 (10000 is the default setting for this parameter). In my test environment with the simulated network delays I set it to 20000 and that allowed me to install modules despite the network delays. So I would recommend to set it to `TimeoutMillis=20000` and if you still run into the issue, gradually set it to something higher like 30000, 40000, etc.

Let me know if this works for you. If so, I can make this configurable via the user interface in the next release.
Also, the crash (window going to blank content) should not happen. That's something I need to analyze separately.

**Comment by hashaway** [comment] 2020-12-23 14:26
> @hashaway
> I think there is a workaround that you could apply to avoid this issue. Do the following:
> 
> 1. Open the file `C:\Users\<your-user-name>\AppData\Roaming\sword\installMgr\InstallMgr.conf` in a text editor that can handle unix line breaks (like Notepad++).
> 2. Under `[General]` there should already be an entry `TimeoutMillis=`. Set this to a value greater than 10000 (10000 is the default setting for this parameter, which corresponds to 10s). In my test environment with the simulated network delays I set it to 20000 and that allowed me to install modules despite the network delays. So I would recommend to set it to `TimeoutMillis=20000` and if you still run into the issue, gradually set it to something higher like 30000, 40000, etc. Whenever you have changed it you need to restart Ezra Project for the change to take effect.
> 
> Let me know if this works for you. If so, I can make this configurable via the user interface in the next release.
> Also, the crash (window going to blank content) should not happen. That's something I need to analyze separately. I created the separate issue #156 for this.

**It is working Now!**
I installed Xiphos and BibleTime. Both took more than 10 seconds to initiate the download process before successfully pulling in the modules.
I then proceeded to do exactly what you said, and set the Timeout value to 20000, and now Ezra Project is also successfully downloading the modules.

Thank you very much for your much appreciated assistance. 

Have a Blessed Day :o)

**Comment by tobias-klein** [comment] 2020-12-23 14:31
Excellent! Merry Christmas to you!

**Comment by tobias-klein** [comment] 2021-10-30 06:58
Closing this, since this will be handled by #157.

**Closed by tobias-klein** 2021-10-30 06:58 UTC
Labels: bug 🐞
