### ISSUE TITLE
Perform the strong number displaying

### ISSUE THREAD

**Issue by LAfricain** [ezra-bible-app/ezra-bible-app#1018] opened 2024-01-21 23:34 UTC
For the moment, when the number of strong is displayed, some useless characters are also displayed. e.g. n="7720">.

**Comment by tobias-klein** [comment] 2024-01-22 07:47
@LAfricain Thanks for reporting this!

I have a few questions:
1. Which version of Ezra Bible App have you been testing with and on wich platform?
2. Did you test with Hebrew Strongs or Greek Strongs?
3. Which version of the Hebrew/Greek Strong's modules have you been testing with?

I had observed some issues after the introduction of StrongsGreek 2.0. I tried to fix those issues in Ezra Bible App 1.13, though. At the moment I cannot reproduce this issue with Ezra Bible App 1.13 - only with older versions.

**Comment by LAfricain** [comment] 2024-01-22 09:21
`    Which version of Ezra Bible App have you been testing with and on wich platform?`
1.12 because 1.13 was not available for Ubuntu
   ` Did you test with Hebrew Strongs or Greek Strongs?`
I use the french version of Strong.
   ` Which version of the Hebrew/Greek Strong's modules have you been testing with?`
Same answer.

**Comment by tobias-klein** [comment] 2024-01-22 17:53
Ok, closing this issue since that bug is fixed in version 1.13 (also available for Ubuntu 22.04).

**Closed** 2024-01-22 18:01 UTC

**Comment by LAfricain** [comment] 2024-01-22 19:23
You don't have a release for Ubuntu. Only debian. May I use the debian?
