### ISSUE TITLE
Updating/replacing an installed module?

### ISSUE THREAD

**Issue by DavidHaslam** [ezra-bible-app/ezra-bible-app#169] opened 2021-01-13 17:59 UTC
AFAICT, to install an update for an already installed module requires first manually removing the module before adding the latest version.

Suggest provide a feature to Update / Replace any installed module when an updated version is available.

**Comment by tobias-klein** [comment] 2021-01-13 19:21
This is a duplicate of #31.

**Closed** 2021-11-07 07:04 UTC
Labels: duplicate
