### ISSUE TITLE
Translations with leading zeros in Strong's #s (eg. H07225) cause the function "Find all occurances" to always return zero results.

### ISSUE THREAD

**Issue by toazd** [ezra-bible-app/ezra-bible-app#1086] opened 2024-07-27 12:37 UTC
Title says it all. Same translation and same versions as the last issue that I had opened.

"King James Version (1769) with Strongs Numbers and Morphology and Catchwords [KJV]"
Version: 3.1 Size 4133 KB
Repository: Crosswire

**Comment by tobias-klein** [comment] 2024-07-27 12:48
This is also fixed by the bugfix I did for #1085, because it has the same root cause. Therefore I'm closing this issue.

**Closed by tobias-klein** 2024-07-27 12:48 UTC

**Comment by toazd** [comment] 2024-07-27 13:07
Ok, thank you!
